package internaciones.ui;

import internaciones.ui.abm.AbmCama;
import internaciones.ui.abm.AbmHabitacion;
import internaciones.ui.abm.AbmInternacion;
import internaciones.ui.abm.AbmUbicacion;

/**
 *
 * @author quevedox
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContenedorPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiUbicacion = new javax.swing.JMenuItem();
        jmiHabitacion = new javax.swing.JMenuItem();
        jmiCama = new javax.swing.JMenuItem();
        jmiInternacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpContenedorPrincipal.setPreferredSize(new java.awt.Dimension(1200, 550));

        javax.swing.GroupLayout jdpContenedorPrincipalLayout = new javax.swing.GroupLayout(jdpContenedorPrincipal);
        jdpContenedorPrincipal.setLayout(jdpContenedorPrincipalLayout);
        jdpContenedorPrincipalLayout.setHorizontalGroup(
            jdpContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jdpContenedorPrincipalLayout.setVerticalGroup(
            jdpContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jmiUbicacion.setText("Ubicacion");
        jmiUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUbicacionActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUbicacion);

        jmiHabitacion.setText("Habitacion");
        jmiHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHabitacionActionPerformed(evt);
            }
        });
        jMenu1.add(jmiHabitacion);

        jmiCama.setText("Cama");
        jmiCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCamaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCama);

        jmiInternacion.setText("Internacion");
        jmiInternacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInternacionActionPerformed(evt);
            }
        });
        jMenu1.add(jmiInternacion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpContenedorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpContenedorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUbicacionActionPerformed
        // TODO add your handling code here:

        AbmUbicacion abmUbicacion = new AbmUbicacion();
        jdpContenedorPrincipal.add(abmUbicacion);
        abmUbicacion.setVisible(true);
    }//GEN-LAST:event_jmiUbicacionActionPerformed

    private void jmiHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHabitacionActionPerformed
        // TODO add your handling code here:
        
        AbmHabitacion abmHabitacion = new AbmHabitacion();
        jdpContenedorPrincipal.add(abmHabitacion);
        abmHabitacion.setVisible(true);
    }//GEN-LAST:event_jmiHabitacionActionPerformed

    private void jmiCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCamaActionPerformed
        // TODO add your handling code here:
        
        AbmCama abmCama = new AbmCama();
        jdpContenedorPrincipal.add(abmCama);
        abmCama.setVisible(true);
    }//GEN-LAST:event_jmiCamaActionPerformed

    private void jmiInternacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInternacionActionPerformed
        // TODO add your handling code here:
        
        AbmInternacion abmInternacion = new AbmInternacion();
        jdpContenedorPrincipal.add(abmInternacion);
        abmInternacion.setVisible(true);
    }//GEN-LAST:event_jmiInternacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JDesktopPane jdpContenedorPrincipal;
    private javax.swing.JMenuItem jmiCama;
    private javax.swing.JMenuItem jmiHabitacion;
    private javax.swing.JMenuItem jmiInternacion;
    private javax.swing.JMenuItem jmiUbicacion;
    // End of variables declaration//GEN-END:variables
}
