package internaciones.ui.abm;

import internaciones.controllers.CamaDAO;
import internaciones.controllers.HabitacionDAO;
import internaciones.models.Cama;
import internaciones.models.Habitacion;
import internaciones.ui.grilla.GrillaCama;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author quevedox
 */
public class AbmCama extends javax.swing.JInternalFrame {
    
    private Cama cama;
    private CamaDAO camaDAO;
    private HabitacionDAO habitacionDAO;
    private GrillaCama grillaCama;
    private DefaultComboBoxModel boxModel;

    /**
     * Creates new form AbmCama
     */
    public AbmCama() {
        initComponents();
        
        camaDAO = new CamaDAO();
        habitacionDAO = new HabitacionDAO();
        ArrayList<Cama> camas = new ArrayList<>();
        try {
            ArrayList<Habitacion> habitaciones = habitacionDAO.read();
            boxModel = new DefaultComboBoxModel(habitaciones.toArray());
            jcbHabitaciones.setModel(boxModel);
        } catch (Exception ex) {
            Logger.getLogger(AbmCama.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            camas = camaDAO.read();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        grillaCama = new GrillaCama(camas);
        jtListadoCamas.setModel(grillaCama);
        
    }
        
    public void limpiarCampos(){
        jtfNumero.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNumero = new javax.swing.JTextField();
        jbAltaCama = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoCamas = new javax.swing.JTable();
        jcbHabitaciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jbModificarCama = new javax.swing.JButton();
        jbBajasCama = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfEstado = new javax.swing.JTextField();

        setClosable(true);

        jtfNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtfNumeroMouseExited(evt);
            }
        });
        jtfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNumeroKeyTyped(evt);
            }
        });

        jbAltaCama.setText("Agregar");
        jbAltaCama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAltaCamaMouseClicked(evt);
            }
        });
        jbAltaCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaCamaActionPerformed(evt);
            }
        });

        jtListadoCamas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoCamas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoCamasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoCamas);

        jcbHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("ID");

        jtfId.setEnabled(false);

        jbModificarCama.setText("Modificar");
        jbModificarCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarCamaActionPerformed(evt);
            }
        });

        jbBajasCama.setText("Eliminar");
        jbBajasCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajasCamaActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero");

        jLabel2.setText("Habitacion");

        jLabel4.setText("Estado");

        jtfEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtfEstadoMouseExited(evt);
            }
        });
        jtfEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfEstadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAltaCama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbModificarCama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBajasCama))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfEstado)
                                .addComponent(jtfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(jtfId)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaCama)
                            .addComponent(jbModificarCama)
                            .addComponent(jbBajasCama)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNumeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNumeroMouseExited
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese más de 3 caracteres");
        }*/
    }//GEN-LAST:event_jtfNumeroMouseExited

    private void jtfNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroKeyTyped
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Ingrese mas de tres caracteres");
        }*/
    }//GEN-LAST:event_jtfNumeroKeyTyped

    private void jbAltaCamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAltaCamaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAltaCamaMouseClicked

    private void jbAltaCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaCamaActionPerformed
        cama = new Cama();

        cama.setNumero(Integer.parseInt(jtfNumero.getText()));
        cama.setEstado(jtfEstado.getText());
        cama.setHabitacion((Habitacion) jcbHabitaciones.getSelectedItem());

        try {
            camaDAO.create(cama);
            limpiarCampos();
        } catch (Exception ex) {
            Logger.getLogger(AbmCama.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoCamas.setModel(new GrillaCama(camaDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(CamaDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAltaCamaActionPerformed

    private void jtListadoCamasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoCamasMouseClicked
        // TODO add your handling code here:
        Cama cama = grillaCama.getCamaFromRow(jtListadoCamas.getSelectedRow());

        jtfId.setText(cama.getId().toString());
        jtfNumero.setText(cama.getNumero().toString());
        jtfEstado.setText(cama.getEstado());
        jcbHabitaciones.setSelectedItem(cama.getHabitacion());
    }//GEN-LAST:event_jtListadoCamasMouseClicked

    private void jbModificarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarCamaActionPerformed
        // TODO add your handling code here:
        cama = new Cama();

        cama.setNumero(Integer.parseInt(jtfNumero.getText()));
        cama.setEstado(jtfEstado.getText());
        cama.setHabitacion((Habitacion) jcbHabitaciones.getSelectedItem());
        cama.setId(Integer.parseInt(jtfId.getText()));

        try {
            camaDAO.update(cama);
        } catch (Exception ex) {
            Logger.getLogger(AbmCama.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoCamas.setModel(new GrillaCama(camaDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModificarCamaActionPerformed

    private void jbBajasCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajasCamaActionPerformed
        cama = new Cama();

        cama.setId(Integer.parseInt(jtfId.getText()));
        try {
            camaDAO.delete(cama);
        } catch (Exception ex) {
            Logger.getLogger(AbmCama.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoCamas.setModel(new GrillaCama(camaDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBajasCamaActionPerformed

    private void jtfEstadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfEstadoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEstadoMouseExited

    private void jtfEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEstadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEstadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaCama;
    private javax.swing.JButton jbBajasCama;
    private javax.swing.JButton jbModificarCama;
    private javax.swing.JComboBox<String> jcbHabitaciones;
    private javax.swing.JTable jtListadoCamas;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNumero;
    // End of variables declaration//GEN-END:variables
}
