package internaciones.ui.abm;

import internaciones.controllers.HabitacionDAO;
import internaciones.controllers.UbicacionDAO;
import internaciones.models.Habitacion;
import internaciones.models.Ubicacion;
import internaciones.ui.grilla.GrillaHabitacion;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author quevedox
 */
public class AbmHabitacion extends javax.swing.JInternalFrame {
    
    private Habitacion habitacion;
    private HabitacionDAO habitacionDAO;
    private UbicacionDAO ubicacionDAO;
    private GrillaHabitacion grillaHabitacion;
    private DefaultComboBoxModel boxModel;

    /**
     * Creates new form AbmHabitacion
     */
    public AbmHabitacion() {
        initComponents();
        
        habitacionDAO = new HabitacionDAO();
        ubicacionDAO = new UbicacionDAO();
        ArrayList<Habitacion> habitaciones = new ArrayList<>();
        try {
            ArrayList<Ubicacion> ubicaciones = ubicacionDAO.read();
            boxModel = new DefaultComboBoxModel(ubicaciones.toArray());
            jcbUbicaciones.setModel(boxModel);
        } catch (Exception ex) {
            Logger.getLogger(AbmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            habitaciones = habitacionDAO.read();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        grillaHabitacion = new GrillaHabitacion(habitaciones);
        jtListadoHabitaciones.setModel(grillaHabitacion);
        
    }
    
    public void limpiarCampos(){
        jtfNumero.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jbModificarHabitacion = new javax.swing.JButton();
        jbBajasHabitacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jbAltaHabitacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoHabitaciones = new javax.swing.JTable();
        jcbUbicaciones = new javax.swing.JComboBox<>();

        setClosable(true);

        jLabel3.setText("ID");

        jtfId.setEnabled(false);

        jbModificarHabitacion.setText("Modificar");
        jbModificarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarHabitacionActionPerformed(evt);
            }
        });

        jbBajasHabitacion.setText("Eliminar");
        jbBajasHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajasHabitacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero");

        jLabel2.setText("Ubicacion");

        jtfNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtfNumeroMouseExited(evt);
            }
        });
        jtfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNumeroKeyTyped(evt);
            }
        });

        jbAltaHabitacion.setText("Agregar");
        jbAltaHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAltaHabitacionMouseClicked(evt);
            }
        });
        jbAltaHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaHabitacionActionPerformed(evt);
            }
        });

        jtListadoHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoHabitacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoHabitaciones);

        jcbUbicaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jtfId)
                            .addComponent(jcbUbicaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAltaHabitacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbModificarHabitacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBajasHabitacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaHabitacion)
                            .addComponent(jbModificarHabitacion)
                            .addComponent(jbBajasHabitacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarHabitacionActionPerformed
        // TODO add your handling code here:
        habitacion = new Habitacion();

        habitacion.setNumero(Integer.parseInt(jtfNumero.getText()));
        habitacion.setUbicacion((Ubicacion) jcbUbicaciones.getSelectedItem());
        habitacion.setId(Integer.parseInt(jtfId.getText()));

        try {
            habitacionDAO.update(habitacion);
        } catch (Exception ex) {
            Logger.getLogger(AbmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoHabitaciones.setModel(new GrillaHabitacion(habitacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbModificarHabitacionActionPerformed

    private void jbBajasHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajasHabitacionActionPerformed
        habitacion = new Habitacion();

        habitacion.setId(Integer.parseInt(jtfId.getText()));
        try {
            habitacionDAO.delete(habitacion);
        } catch (Exception ex) {
            Logger.getLogger(AbmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoHabitaciones.setModel(new GrillaHabitacion(habitacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbBajasHabitacionActionPerformed

    private void jtfNumeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNumeroMouseExited
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese más de 3 caracteres");
        }*/
    }//GEN-LAST:event_jtfNumeroMouseExited

    private void jtfNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroKeyTyped
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Ingrese mas de tres caracteres");
        }*/
    }//GEN-LAST:event_jtfNumeroKeyTyped

    private void jbAltaHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAltaHabitacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAltaHabitacionMouseClicked

    private void jbAltaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaHabitacionActionPerformed
        habitacion = new Habitacion();

        habitacion.setNumero(Integer.parseInt(jtfNumero.getText()));
        habitacion.setUbicacion((Ubicacion) jcbUbicaciones.getSelectedItem());

        try {
            habitacionDAO.create(habitacion);
            limpiarCampos();
        } catch (Exception ex) {
            Logger.getLogger(AbmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoHabitaciones.setModel(new GrillaHabitacion(habitacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAltaHabitacionActionPerformed

    private void jtListadoHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoHabitacionesMouseClicked
        // TODO add your handling code here:
        Habitacion habitacion = grillaHabitacion.getHabitacionFromRow(jtListadoHabitaciones.getSelectedRow());

        jtfId.setText(habitacion.getId().toString());
        jtfNumero.setText(habitacion.getNumero().toString());
        jcbUbicaciones.setSelectedItem(habitacion.getUbicacion());
    }//GEN-LAST:event_jtListadoHabitacionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaHabitacion;
    private javax.swing.JButton jbBajasHabitacion;
    private javax.swing.JButton jbModificarHabitacion;
    private javax.swing.JComboBox<String> jcbUbicaciones;
    private javax.swing.JTable jtListadoHabitaciones;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNumero;
    // End of variables declaration//GEN-END:variables
}
