package internaciones.ui.abm;

import internaciones.controllers.CamaDAO;
import internaciones.controllers.InternacionDAO;
import internaciones.models.Cama;
import internaciones.models.Internacion;
import internaciones.ui.grilla.GrillaInternacion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author quevedox
 */
public class AbmInternacion extends javax.swing.JInternalFrame {
    
    private Internacion internacion;
    private InternacionDAO internacionDAO;
    private CamaDAO camaDAO;
    private GrillaInternacion grillaInternacion;
    private DefaultComboBoxModel boxModel;

    /**
     * Creates new form AbmInternacion
     */
    public AbmInternacion() {
        initComponents();
        
        internacionDAO = new InternacionDAO();
        camaDAO = new CamaDAO();
        ArrayList<Internacion> internaciones = new ArrayList<>();
        try {
            ArrayList<Cama> camas = camaDAO.read();
            boxModel = new DefaultComboBoxModel(camas.toArray());
            jcbCamas.setModel(boxModel);
        } catch (Exception ex) {
            Logger.getLogger(AbmCama.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            internaciones = internacionDAO.read();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        grillaInternacion = new GrillaInternacion(internaciones);
        jtListadoInternaciones.setModel(grillaInternacion);
    }
    
    public void limpiarCampos(){
        jtfPaciente.setText("");
        jtfFecha.setText("");
        jtfDiagnostico.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfId = new javax.swing.JTextField();
        jbModificarInternacion = new javax.swing.JButton();
        jbBajasInternacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfPaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbAltaInternacion = new javax.swing.JButton();
        jtfFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoInternaciones = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtfDiagnostico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbCamas = new javax.swing.JComboBox<>();

        setClosable(true);

        jtfId.setEnabled(false);

        jbModificarInternacion.setText("Modificar");
        jbModificarInternacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarInternacionActionPerformed(evt);
            }
        });

        jbBajasInternacion.setText("Eliminar");
        jbBajasInternacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajasInternacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Paciente");

        jLabel2.setText("Diagnostico");

        jtfPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtfPacienteMouseExited(evt);
            }
        });
        jtfPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPacienteKeyTyped(evt);
            }
        });

        jLabel4.setText("Fecha (dd/MM/yyyy)");

        jbAltaInternacion.setText("Agregar");
        jbAltaInternacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAltaInternacionMouseClicked(evt);
            }
        });
        jbAltaInternacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaInternacionActionPerformed(evt);
            }
        });

        jtfFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtfFechaMouseExited(evt);
            }
        });
        jtfFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFechaKeyTyped(evt);
            }
        });

        jtListadoInternaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoInternaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoInternacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoInternaciones);

        jLabel3.setText("ID");

        jtfDiagnostico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtfDiagnosticoMouseExited(evt);
            }
        });
        jtfDiagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDiagnosticoKeyTyped(evt);
            }
        });

        jLabel5.setText("Cama");

        jcbCamas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jbAltaInternacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbModificarInternacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBajasInternacion))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbCamas, 0, 270, Short.MAX_VALUE)
                            .addComponent(jtfDiagnostico)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(jtfPaciente)
                            .addComponent(jtfId))))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaInternacion)
                            .addComponent(jbModificarInternacion)
                            .addComponent(jbBajasInternacion)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarInternacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarInternacionActionPerformed
        // TODO add your handling code here:
        internacion = new Internacion();
        
        String fechaTexto = jtfFecha.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date fecha = dateFormat.parse(fechaTexto);
            internacion.setFecha(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(AbmInternacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        internacion.setPaciente(jtfPaciente.getText());
        internacion.setDiagnostico(jtfDiagnostico.getText());
        internacion.setCama((Cama) jcbCamas.getSelectedItem());
        internacion.setId(Integer.parseInt(jtfId.getText()));

        try {
            internacionDAO.update(internacion);
        } catch (Exception ex) {
            Logger.getLogger(AbmInternacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoInternaciones.setModel(new GrillaInternacion(internacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmInternacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModificarInternacionActionPerformed

    private void jbBajasInternacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajasInternacionActionPerformed
        internacion = new Internacion();

        internacion.setId(Integer.parseInt(jtfId.getText()));
        try {
            internacionDAO.delete(internacion);
        } catch (Exception ex) {
            Logger.getLogger(InternacionDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoInternaciones.setModel(new GrillaInternacion(internacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmInternacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBajasInternacionActionPerformed

    private void jtfPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfPacienteMouseExited
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese más de 3 caracteres");
        }*/
    }//GEN-LAST:event_jtfPacienteMouseExited

    private void jtfPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPacienteKeyTyped
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Ingrese mas de tres caracteres");
        }*/
    }//GEN-LAST:event_jtfPacienteKeyTyped

    private void jbAltaInternacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAltaInternacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAltaInternacionMouseClicked

    private void jbAltaInternacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaInternacionActionPerformed
        internacion = new Internacion();
        
        String fechaTexto = jtfFecha.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date fecha = dateFormat.parse(fechaTexto);
            internacion.setFecha(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(AbmInternacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        internacion.setPaciente(jtfPaciente.getText());
        internacion.setDiagnostico(jtfDiagnostico.getText());
        internacion.setCama((Cama) jcbCamas.getSelectedItem());

        try {
            internacionDAO.create(internacion);
            limpiarCampos();
        } catch (Exception ex) {
            Logger.getLogger(AbmInternacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoInternaciones.setModel(new GrillaInternacion(internacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(InternacionDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAltaInternacionActionPerformed

    private void jtfFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfFechaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaMouseExited

    private void jtfFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaKeyTyped

    private void jtListadoInternacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoInternacionesMouseClicked
        // TODO add your handling code here:
        Internacion internacion = grillaInternacion.getInternacionFromRow(jtListadoInternaciones.getSelectedRow());

        jtfId.setText(internacion.getId().toString());
        jtfPaciente.setText(internacion.getPaciente());
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Define el formato deseado
        String fechaTexto = dateFormat.format(internacion.getFecha());
        jtfFecha.setText(fechaTexto);
        
        jtfDiagnostico.setText(internacion.getDiagnostico());
        jcbCamas.setSelectedItem(internacion.getCama());
    }//GEN-LAST:event_jtListadoInternacionesMouseClicked

    private void jtfDiagnosticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfDiagnosticoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiagnosticoMouseExited

    private void jtfDiagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDiagnosticoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiagnosticoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaInternacion;
    private javax.swing.JButton jbBajasInternacion;
    private javax.swing.JButton jbModificarInternacion;
    private javax.swing.JComboBox<String> jcbCamas;
    private javax.swing.JTable jtListadoInternaciones;
    private javax.swing.JTextField jtfDiagnostico;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfPaciente;
    // End of variables declaration//GEN-END:variables
}
