package internaciones.ui.abm;

import internaciones.controllers.UbicacionDAO;
import internaciones.ui.grilla.GrillaUbicacion;
import internaciones.models.Ubicacion;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;

/**
 *
 * @author quevedox
 */
public class AbmUbicacion extends javax.swing.JInternalFrame {
    
    private Ubicacion ubicacion;
    private UbicacionDAO ubicacionDAO;
    private GrillaUbicacion grillaUbicacion;
    
    public AbmUbicacion() {
        initComponents();
        
        ubicacionDAO = new UbicacionDAO();
        ArrayList<Ubicacion> ubicaciones = new ArrayList();
        
        try {
            ubicaciones = ubicacionDAO.read();
        } catch (Exception e) {
            e.printStackTrace ();
        }
        
        grillaUbicacion = new GrillaUbicacion(ubicaciones);
        jtListadoUbicaciones.setModel(grillaUbicacion);
        
    }
    
    public void limpiarCampos(){
        jtfHospital.setText("");
        jtfNombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jbModificarUbicacion = new javax.swing.JButton();
        jbBajasUbicacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfHospital = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jbAltaUbicacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoUbicaciones = new javax.swing.JTable();

        setClosable(true);

        jLabel3.setText("ID");

        jtfId.setEnabled(false);

        jbModificarUbicacion.setText("Modificar");
        jbModificarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarUbicacionActionPerformed(evt);
            }
        });

        jbBajasUbicacion.setText("Eliminar");
        jbBajasUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajasUbicacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Hospital");

        jLabel2.setText("Nombre");

        jtfHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtfHospitalMouseExited(evt);
            }
        });
        jtfHospital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfHospitalKeyTyped(evt);
            }
        });

        jbAltaUbicacion.setText("Agregar");
        jbAltaUbicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAltaUbicacionMouseClicked(evt);
            }
        });
        jbAltaUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaUbicacionActionPerformed(evt);
            }
        });

        jtListadoUbicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoUbicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoUbicacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoUbicaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfHospital)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jtfId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbAltaUbicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbModificarUbicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBajasUbicacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaUbicacion)
                            .addComponent(jbModificarUbicacion)
                            .addComponent(jbBajasUbicacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarUbicacionActionPerformed
        // TODO add your handling code here:
        ubicacion = new Ubicacion();
        
        ubicacion.setHospital(jtfHospital.getText());
        ubicacion.setNombre(jtfNombre.getText());
        ubicacion.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            ubicacionDAO.update(ubicacion);
        } catch (Exception ex) {
            Logger.getLogger(AbmUbicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtListadoUbicaciones.setModel(new GrillaUbicacion(ubicacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmUbicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbModificarUbicacionActionPerformed

    private void jbBajasUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajasUbicacionActionPerformed
        ubicacion = new Ubicacion();

        ubicacion.setId(Integer.parseInt(jtfId.getText()));
        try {
            ubicacionDAO.delete(ubicacion);
        } catch (Exception ex) {
            Logger.getLogger(AbmUbicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoUbicaciones.setModel(new GrillaUbicacion(ubicacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmUbicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jbBajasUbicacionActionPerformed

    private void jtfHospitalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfHospitalMouseExited
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese más de 3 caracteres");
        }*/
    }//GEN-LAST:event_jtfHospitalMouseExited

    private void jtfHospitalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfHospitalKeyTyped
        // TODO add your handling code here:
        /*if(jtfDenominacion.getText().length() <= 3){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Ingrese mas de tres caracteres");
        }*/
    }//GEN-LAST:event_jtfHospitalKeyTyped

    private void jbAltaUbicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAltaUbicacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAltaUbicacionMouseClicked

    private void jbAltaUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaUbicacionActionPerformed
        ubicacion = new Ubicacion();

        ubicacion.setHospital(jtfHospital.getText());
        ubicacion.setNombre(jtfNombre.getText());

        try {
            ubicacionDAO.create(ubicacion);
            limpiarCampos();
        } catch (Exception ex) {
            Logger.getLogger(AbmUbicacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoUbicaciones.setModel(new GrillaUbicacion(ubicacionDAO.read()));
        } catch (Exception ex) {
            Logger.getLogger(AbmUbicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAltaUbicacionActionPerformed

    private void jtListadoUbicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoUbicacionesMouseClicked
        // TODO add your handling code here:
        Ubicacion ubicacion = grillaUbicacion.getUbicacionFromRow(jtListadoUbicaciones.getSelectedRow());

        jtfHospital.setText(ubicacion.getHospital());
        jtfNombre.setText(ubicacion.getNombre());
        jtfId.setText(ubicacion.getId().toString());

    }//GEN-LAST:event_jtListadoUbicacionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaUbicacion;
    private javax.swing.JButton jbBajasUbicacion;
    private javax.swing.JButton jbModificarUbicacion;
    private javax.swing.JTable jtListadoUbicaciones;
    private javax.swing.JTextField jtfHospital;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
